version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cryptotradeai-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - cryptotradeai-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cryptotradeai-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://root:your_mongodb_password@mongodb:27017/cryptotradeai?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://184.73.5.19
      - WS_URL=ws://184.73.5.19
      - LOG_LEVEL=info
      - LOG_FILE=logs/app.log
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cryptotradeai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cryptotradeai-client
    restart: always
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://184.73.5.19/api
      - NEXT_PUBLIC_WS_URL=ws://184.73.5.19
      - NEXT_PUBLIC_JWT_SECRET=your_jwt_secret_key
      - NEXT_PUBLIC_JWT_EXPIRES_IN=7d
      - NEXT_PUBLIC_ENABLE_ANALYTICS=true
      - NEXT_PUBLIC_ENABLE_NOTIFICATIONS=true
      - NEXT_PUBLIC_THEME=dark
      - NEXT_PUBLIC_LANGUAGE=en
      - NEXT_PUBLIC_DEFAULT_EXCHANGE=binance
      - NEXT_PUBLIC_DEFAULT_PAIR=BTC/USDT
      - NEXT_PUBLIC_DEFAULT_TIMEFRAME=1h
      - NEXT_PUBLIC_ENABLE_MONITORING=true
      - NEXT_PUBLIC_MONITORING_INTERVAL=60000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - cryptotradeai-network

networks:
  cryptotradeai-network:
    driver: bridge

volumes:
  mongodb_data: 